### ISSUE TITLE
[Question]: why `@babel/runtime` is necessary in Module solution

### ISSUE THREAD

**Issue by lianghx-319** [modern-js-dev/modern.js#307]
Just for curiosity.

**Comment by targeral** [comment]
The build function is provided in the module solution via Module-tools. Module-tools is based on [Babel](https://babeljs.io/) for source code building, where [transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) is used in the Babel configuration. The plugin injected helper code to save on codesize. When using this plugin, the project needs to use @babel/runtime as a dependency. More details can be viewed by this link: [https://babeljs.io/docs/en/babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime#why)

**Comment by lianghx-319** [comment]
so, it is difficult to integrate `swc` or `esbuild` as build tools for node only library?

**Comment by targeral** [comment]
Initially, the intention was to use esbuild as it is a very fast build. However, after some research, we found that there were some limitations to using esbuild. Since module-tools has to support the generation of ES5 build products, esbuild currently has no way of targeting ES5 language versions for building.  So for the time being babel is used as a tool for building code.

However, in the future we will consider replacing the current solution of using babel for code building.
